import turtle

def jump(penX):
    penX.setheading(0)
    penX.forward(100)
    penX.setheading(-60)
    penX.forward(35)
    penX.setheading(70)
    penX.forward(70)
    penX.setheading(-75)
    penX.forward(130)
    penX.setheading(80)
    penX.forward(170)
    penX.setheading(-75)
    penX.forward(100)
    penX.setheading(60)
    penX.forward(22)

pen1=turtle.Pen()
pen2=turtle.Pen()
pen3=turtle.Pen()
pen1.hideturtle()
pen2.hideturtle()
pen3.hideturtle()
pen1.color('red')
pen2.color('white')
pen3.color('purple')
pen1.pensize(8)
pen2.pensize(10)
pen1.speed(10)

pen3.penup()
pen3.goto(300,200)
pen3.write('心动的感觉',font=('隶书',40,'normal'))

for _ in range(5):
    pen1.pendown()
    pen1.setheading(0)
    pen1.forward(120)
    pen1.setheading(-75)
    pen1.forward(50)
    pen1.setheading(80)
    pen1.forward(120)
    pen1.setheading(-85)
    pen1.forward(190)
    pen1.setheading(80)
    pen1.forward(300)
    pen1.setheading(-89)
    pen1.forward(180)
    pen1.setheading(0)
    
turtle.clear()
